---
# Package categories and their available options
# This file is used by both the option selector and Ansible

monitoring_apps:
  - htop
  - btop
  - atop
  - glances

browsers:
  - firefox
  - chromium
  - brave
  - vivaldi
  - zen
