---
- name: Setup Arch Linux system
  hosts: localhost
  vars:
    # Default applications if no selection is provided
    monitoring_apps: ["htop"]
    browsers: ["firefox"]
  tasks:
      
    - name: Load package configuration
      include_vars: "{{ ansible_env.HOME }}/mydotfiles/arch/packages.yml"

    - name: Display selected monitoring applications
      debug:
        msg: "Installing monitoring applications: {{ monitoring_apps }}"

    - name: Display selected browsers
      debug:
        msg: "Installing browsers: {{ browsers }}"
      
    - name: Ensure system is up to date
      pacman:
        update_cache: yes
        upgrade: yes
      become: yes

    - name: Install selected monitoring applications
      shell: yay -S --noconfirm {{ item }}
      loop: "{{ monitoring_apps }}"
      when: monitoring_apps is defined and monitoring_apps | length > 0

    - name: Install selected browsers
      shell: yay -S --noconfirm {{ item }}
      loop: "{{ browsers }}"
      when: browsers is defined and browsers | length > 0

    - name: Get all available monitoring applications from config
      set_fact:
        all_monitoring_apps: "{{ available_monitoring_apps }}"

    - name: Get all available browsers from config
      set_fact:
        all_browsers: "{{ available_browsers }}"

    - name: Remove unselected monitoring applications
      shell: yay -Rns --noconfirm {{ item }}
      loop: "{{ all_monitoring_apps | difference(monitoring_apps | default([])) }}"
      failed_when: false  # Don't fail if package is not installed

    - name: Remove unselected browsers
      shell: yay -Rns --noconfirm {{ item }}
      loop: "{{ all_browsers | difference(browsers | default([])) }}"
      failed_when: false  # Don't fail if package is not installed

    - name: Save installed selections for next run
      shell: |
        echo "{{ monitoring_apps | join(',') }}" > {{ ansible_env.HOME }}/.dotfiles_monitoring
        echo "{{ browsers | join(',') }}" > {{ ansible_env.HOME }}/.dotfiles_browsers
      when: (monitoring_apps is defined and monitoring_apps | length > 0) or (browsers is defined and browsers | length > 0)