---
- name: Setup Arch Linux system
  hosts: localhost
  vars:
    # Default applications if no selection is provided (will be overridden by selections)
    monitoring_apps: ["htop"]
    browsers: ["firefox"] 
    gaming_apps: ["steam"]
    terminal_apps: []
    code_editors: []
  tasks:
      
    - name: Load package configuration
      include_vars: "packages.yml"

    - name: Get all package categories dynamically
      set_fact:
        package_categories: "{{ vars.keys() | select('match', '^(monitoring_apps|browsers|gaming_apps|terminal_apps|code_editors)$') | list }}"

    - name: Display all selected applications
      debug:
        msg: "Installing {{ item | replace('_', ' ') }}: {{ vars[item] | default([]) }}"
      loop: "{{ package_categories }}"
      when: vars[item] is defined and vars[item] | length > 0

    - name: Ensure system is up to date
      pacman:
        update_cache: yes
        upgrade: yes
      become: yes

    - name: Install selected applications for all categories
      shell: |
        if [[ "{{ item.1 }}" == *"-bin" ]]; then
          BASE_NAME=$(echo "{{ item.1 }}" | sed 's/-bin$//')
          if pacman -Qi "$BASE_NAME" >/dev/null 2>&1; then
            echo "Removing conflicting package: $BASE_NAME"
            yay -Rns --noconfirm "$BASE_NAME" || true
          fi
        fi
        yay -S --noconfirm {{ item.1 }}
      loop: >
        {%- set result = [] -%}
        {%- for category in package_categories -%}
          {%- if vars[category] is defined -%}
            {%- for app in vars[category] -%}
              {{- result.append([category, app]) or '' -}}
            {%- endfor -%}
          {%- endif -%}
        {%- endfor -%}
        {{ result }}
      when: item.1 is defined

    - name: Get packages to remove
      set_fact:
        packages_to_remove: >
          {%- set result = [] -%}
          {%- for category in package_categories -%}
            {%- set available_packages = vars[category + '_available'] | default(vars[category]) -%}
            {%- set selected_packages = vars[category + '_selected'] | default(vars[category]) -%}
            {%- if available_packages is defined -%}
              {%- for pkg_info in available_packages -%}
                {%- set pkg_name = pkg_info.package_name -%}
                {%- if selected_packages is not defined or pkg_name not in selected_packages -%}
                  {{- result.append([category, pkg_name]) or '' -}}
                {%- endif -%}
              {%- endfor -%}
            {%- endif -%}
          {%- endfor -%}
          {{ result }}

    - name: Display packages to remove
      debug:
        msg: "Removing {{ item.0 | replace('_', ' ') }}: {{ item.1 }}"
      loop: "{{ packages_to_remove }}"
      when: packages_to_remove | length > 0

    - name: Remove deselected applications for all categories
      shell: yay -Rns --noconfirm {{ item.1 }} || true
      loop: "{{ packages_to_remove }}"
      when: packages_to_remove | length > 0

    - name: Save installed selections for next run
      shell: |
        mkdir -p ../.saved_selections
        {% for category in package_categories %}
        echo "{{ vars[category] | default([]) | join(',') }}" > ../.saved_selections/{{ category }}
        {% endfor %}