---
- name: Setup Arch Linux system
  hosts: localhost
  become: true
  tasks:
    - name: Ensure system is up to date
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install essential packages
      pacman:
        name:
          - curl
        state: present

    - name: Select system monitoring tools
      options_prompt:
        category: "System Monitoring"
        options:
          - htop
          - btop
          - neofetch
          - tree
          - ncdu
        preselected:
          - htop
          - btop
      register: monitoring_selection
      delegate_to: localhost

    - name: Show monitoring tools selection
      debug:
        msg: 
          - "Category: {{ monitoring_selection.category }}"
          - "Selected tools: {{ monitoring_selection.selected_options }}"

    - name: Install selected monitoring tools
      shell: yay -S --needed --noconfirm {{ item }}
      loop: "{{ monitoring_selection.selected_options }}"
      when: monitoring_selection.selected_options | length > 0
    

